erDiagram

  dim_stage_01 {
    id string
    v1 string
  }

  dim_stage_02 {
    id string
    v2 string
  }

  dim_stage_03 {
    id string
    v3 string
  }

  dim_stage_04 {
    id string
    v4 string
  }

  dim_stage_05 {
    id string
    v5 string
  }

