erDiagram

  users {
    user_id integer
    email varchar
  }

  orders {
    order_id integer
    user_id integer
    amount decimal
  }

  items {
    item_id integer
    order_id integer
    product varchar
  }

  %% Relationships
  users ||--o{ orders : "user_id"
  orders ||--o{ items : "order_id"

