erDiagram

  fct_order {
    order_sk bigint
    order_id string
    customer_sk bigint
    product_sk bigint
    order_amount decimal_14
    currency string
    order_ts timestamp
    payment_type string
    is_chargeback boolean
  }

  %% Relationships
  dim_customer ||--o{ fct_order : "customer_sk"
  dim_product ||--o{ fct_order : "product_sk"

