project: "my-project"
version: "1.0"
owners:
  - "team@example.com"

sources:
  - id: source_db
    kind: postgres
    db: source_database
    description: "Source database"

targets:
  - db: dw
    engine: postgres
    schema: public
    tables:
      - name: example_table
        description: "Example target table"
        columns:
          - name: id
            type: INTEGER
            pk: true
            description: "Primary key"
          
          - name: name
            type: VARCHAR(255)
            not_null: true
            description: "Name field"
          
          - name: created_at
            type: TIMESTAMP
            default: now()
            description: "Creation timestamp"

mappings:
  - target: dw.public.example_table.name
    from:
      source_id: source_db
      path: $.user.name
      transform: trim()
    notes: "Map user name from source"
